// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0bZ_t7tbAeXX-qiPfnSRmz0N83CTUzDs',
    appId: '1:1005669714242:web:177d00abc389a62fb860db',
    messagingSenderId: '1005669714242',
    projectId: 'pmproject-bb2b3',
    authDomain: 'pmproject-bb2b3.firebaseapp.com',
    storageBucket: 'pmproject-bb2b3.firebasestorage.app',
    measurementId: 'G-Q3CERFCSQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78291rgkNnVyWlX9BU1hNacm6NAdgEiI',
    appId: '1:1005669714242:android:c68e9ca72b2b1ac8b860db',
    messagingSenderId: '1005669714242',
    projectId: 'pmproject-bb2b3',
    storageBucket: 'pmproject-bb2b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEIurjOFfHMCstWMOJHWlWxvRsvFJldC0',
    appId: '1:1005669714242:ios:3d09ef15b3a8f225b860db',
    messagingSenderId: '1005669714242',
    projectId: 'pmproject-bb2b3',
    storageBucket: 'pmproject-bb2b3.firebasestorage.app',
    iosBundleId: 'com.example.pmMobileFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEIurjOFfHMCstWMOJHWlWxvRsvFJldC0',
    appId: '1:1005669714242:ios:3d09ef15b3a8f225b860db',
    messagingSenderId: '1005669714242',
    projectId: 'pmproject-bb2b3',
    storageBucket: 'pmproject-bb2b3.firebasestorage.app',
    iosBundleId: 'com.example.pmMobileFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0bZ_t7tbAeXX-qiPfnSRmz0N83CTUzDs',
    appId: '1:1005669714242:web:e399ed3850b99b07b860db',
    messagingSenderId: '1005669714242',
    projectId: 'pmproject-bb2b3',
    authDomain: 'pmproject-bb2b3.firebaseapp.com',
    storageBucket: 'pmproject-bb2b3.firebasestorage.app',
    measurementId: 'G-K38RH3F4NP',
  );
}
